name: "Check that my NPM packages are available on npmjs.com"
on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch: {}

jobs:
  check_availability:
    name: "Fetch packages"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Install Node"
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: "Fetch packages"
        run: node check-package-availability.ts
