name: "Check that my NPM packages are available on npmjs.com"
on:
  schedule:
    - cron: "17 * * * *"

jobs:
  check_availability:
    name: "Install packages"
    runs-on: ubuntu-latest
    steps:
      - name: "Install NPM"
        uses: actions/setup-node@v6
        with:
          node-version: latest
      - name: "Install packages"
        run: npm install cmath-js --prefer-online --cache ./cache
